version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KEYCLOAK_HOSTNAME: 13.95.171.231
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/fullchain.pem
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/privkey.pem
    volumes:
      - ./certs:/opt/keycloak/certs:ro
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    command: start --https-port=8443 --hostname=13.95.171.231
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge