name: Configure VM with Ansible

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Output (ensure applied)
        working-directory: ./terraform
        run: terraform output -json

      - name: Generate Ansible inventory dynamically
        run: |
          chmod +x ./ansible/inventory_dynamic.py
          python3 ./ansible/inventory_dynamic.py > ./ansible/inventory.json

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.json main.yml

      - name: Cleanup Temporary Private Key
        if: always()
        run: |
          TEMP_KEY=$(jq -r '.all.vars.ansible_ssh_private_key_file' ./ansible/inventory.json)
          echo "Deleting temporary key: $TEMP_KEY"
          rm -f "$TEMP_KEY"